name: keygen
description: Dart package for Keygen (https://keygen.sh)

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.4.3

dependencies:
  openapi:
    path: ../openapi

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  dotenv: ^4.2.0
  machineid:
    path: ../machineid
